#ifndef CHAT_IDL_
#define CHAT_IDL_

module My {
    module Type {
        module Chat {
            const long CONTENT_STR_SIZE = 128;

            struct Obj {
                string<CONTENT_STR_SIZE> content; // content of the chat object
            };
        };
    };
};

// Names
module My {
    module Topic {
        module Chat {
            const string TOPIC      = "Chat";
            const string TYPE       = "My::Type::Chat::Obj";
        };
    };
};
#endif /* CHAT_IDL_ */