module My {
	const long MSG_LEN=256;
	
	struct ChatObject {
			string<MSG_LEN> msg;
	};
		
	const string CHAT_TOPIC_NAME = "Chat";
};








































/*
	module Chat {
		struct Object {
			string<MSG_LEN> msg;
		};
	
		const string TOPIC_NAME = "Chat/v1";
	};
};
*/