
#ifndef CHAT_IDL_
#define CHAT_IDL_

module My {
    module Type {
        module Chat {
            const long ID_STR_SIZE      = 32;
            const long CONTENT_STR_SIZE = 128;

            struct Obj {
                @key string<ID_STR_SIZE> id;      // identity of the chat object
                string<CONTENT_STR_SIZE> content; // content of the chat object
            };
        };
    };
};

// Names defined the DDS-XML file: if/MyService.xml 
module My {
    module Topic {
        module Chat {
            const string TOPIC      = "Chat";
            const string TYPE       = "My::Type::Chat::Obj";
            const string WRITER     = "_pub::Chat_writer";
            const string READER     = "_sub::Chat_reader";
        };
    };
    module If { 
        const string PUB            = "MyServiceIfLib::Pub";
        const string SUB            = "MyServiceIfLib::Sub";
        const string PUBSUB         = "MyServiceIfLib::PubSub";
    };
};
#endif /* CHAT_IDL_ */