// This is a single lineIDL comment
/* This is a multi-line IDL comment */

//@copy        // This gets copied verbatim in all languages    
//@copy-c      // This gets copied verbatim in C and C++ only
//@copy-cppcli // This gets copied verbatim in .NET C++/CLI
//@copy-java   // This gets copied verbatim in Java only

module My {
    
    const long MAX_SIZE=4096;

    struct ChatObject {
        @key string<MAX_SIZE> id; // identity of the chat object 
        string<MAX_SIZE> content; // content of the chat object        
    }; 

    module name {
        const string CHAT_TOPIC      = "Chat";
        const string CHAT_TYPE       = "My::ChatObject";

        const string CHAT_PUB_IF     = "ChatIfLib::Chat_Pub";
        const string CHAT_SUB_IF     = "ChatIfLib::Chat_Sub";

        const string CHAT_PUBLISHER  = "_pub";
        const string CHAT_SUBSCRIBER = "_sub";

        const string CHAT_WRITER     = "_pub::Chat_writer";
        const string CHAT_READER     = "_sub::Chat_reader";
    };
};
